[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
host = { path = "../host" }

db-access = { git = "https://github.com/OilerNetwork/fossil-offchain-processor.git", branch = "block-validity-deps-segregation" }
mmr-accumulator = { git = "https://github.com/OilerNetwork/fossil-offchain-processor.git", branch = "block-validity-deps-segregation" }

starknet = "0.12.0"
dotenv = "0.15.0"
tokio = { version = "1.41.1", features = ["full"] }
alloy = { version = "0.6.4", features = ["network", "providers"] }
eyre = "0.6.10"
tracing = "0.1.39"
tracing-subscriber = "0.3.18"

# [lints]
# workspace = true
