[workspace]
resolver = "2"
members = [
    "crates/starknet-handler",
    "crates/client",
    "crates/relayer",
    "crates/common",
    "crates/methods",
    "crates/host",
    "crates/guest-types",
    "crates/ethereum",
    "crates/mmr-utils",
]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[workspace.dependencies]
eth-rlp-types = { git = "https://github.com/ametel01/eth-rlp-verify.git" }
eth-rlp-verify = { git = "https://github.com/ametel01/eth-rlp-verify.git" }
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs.git", branch = "master" }

sqlx = { version = "0.8.2", features = [
    "postgres",
    "runtime-tokio-native-tls",
] }
eyre = "0.6"
thiserror = "2.0.3"
tracing = "0.1.40"
tokio = "1.41.1"
dotenv = "0.15"
starknet-crypto = "0.7.3"
clap = "4.5"
