[workspace]
resolver = "2"
members = [
    "crates/starknet-handler",
    "crates/client",
    "crates/relayer",
    "crates/common",
    "crates/methods",
    "crates/publisher",
    "crates/guest-types",
    "crates/ethereum",
    "crates/mmr-utils", 
    "crates/guest-mmr",
]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[workspace.dependencies]
eth-rlp-types = { git = "https://github.com/ametel01/eth-rlp-verify.git" }
eth-rlp-verify = { git = "https://github.com/ametel01/eth-rlp-verify.git" }
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs.git", branch = "master" }
starknet-crypto = { git = "https://github.com/xJonathanLEI/starknet-rs.git", branch = "master" }

sqlx = { version = "0.8.2", features = [
    "postgres",
    "runtime-tokio-native-tls",
] }
eyre = "0.6"
thiserror = "2.0.4"
tracing = "0.1.40"
tokio = "1.41.1"
dotenv = "0.15"
clap = { version = "4.4.11", features = ["derive"] }

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes.git", tag = "sha2-v0.10.8-risczero.0" }
starknet-crypto = { git = "https://github.com/xJonathanLEI/starknet-rs.git", branch = "master" }