[workspace]
resolver = "2"
members = [
    "crates/starknet-handler",
    "crates/client",
    "crates/relayer",
    "crates/common",
    "crates/methods",
    "crates/host",
    "crates/guest-types",
    "crates/ethereum",
    "crates/mmr-utils",
]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[workspace.dependencies]
eyre = "0.6"
thiserror = "2.0.3"
tracing = "0.1.40"
tokio = "1.41.1"
dotenv = "0.15"
starknet = "0.12.0"

[workspace.lints.clippy]
single_match = "warn"
single_match_else = "warn"
needless_match = "warn"
needless_late_init = "warn"
redundant_pattern_matching = "warn"
redundant_pattern = "warn"
redundant_guards = "warn"
collapsible_match = "warn"
match_single_binding = "warn"
match_same_arms = "warn"
match_ref_pats = "warn"
match_bool = "warn"
needless_bool = "deny"
unwrap_used = "warn"
expect_used = "warn"
