version: "3.8"

services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    env_file:
      - .env
    command: >
      anvil
      --fork-url ${ETH_RPC_URL}
      --block-time 12
      --host 0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5

  katana:
    image: dojoengine/katana:latest
    ports:
      - "5050:5050"
    volumes:
      - ./config:/app/config
    depends_on:
      anvil:
        condition: service_healthy
    command: >
      katana
      --messaging /app/config/anvil.messaging.json
      --disable-fee
      --disable-validate
      --host 0.0.0.0

  contract-deployer:
    build:
      context: .
      dockerfile: Dockerfile.deployer
    env_file:
      - .env
    volumes:
      - ./contracts:/app/contracts
      - ./scripts:/app/scripts
    depends_on:
      - anvil
      - katana
    command: >
      sh -c "
        cd /app/contracts/ethereum &&
        forge script script/LocalTesting.s.sol:LocalSetup --broadcast --rpc-url $$ANVIL_URL &&
        cd /app/scripts/katana &&
        ./deploy.sh
      "

  light-client:
    build:
      context: .
      dockerfile: Dockerfile.rust
    volumes:
      - ./crates:/app/crates
    depends_on:
      - contract-deployer
    command: >
      sh -c "cd /app/crates/client && cargo run"

  relayer:
    build:
      context: .
      dockerfile: Dockerfile.rust
    volumes:
      - ./crates:/app/crates
    depends_on:
      - light-client
    command: >
      sh -c "cd /app/crates/relayer && cargo run" 