[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
host = { path = "../host" }
starknet-handler = { path = "../starknet-handler" }

mmr-accumulator = { git = "https://github.com/OilerNetwork/fossil-offchain-processor.git", branch = "block-validity-deps-segregation" }
common = { path = "../common" }
starknet = "0.12.0"
tokio = { version = "1.41.1", features = ["full"] }
eyre = "0.6.10"
tracing = "0.1.39"

[lints]
workspace = true
