[package]
name = "ethereum"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = { workspace = true }
tracing = { workspace = true }
dotenv = { workspace = true }

alloy = { version = "0.4", features = ["full", "node-bindings"] }

# [lints]
# workspace = true
