[package]
name = "ethereum"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.4", features = ["full", "node-bindings"] }
dotenv = "0.15.0"
eyre = "0.6.12"
tracing = "0.1.39"

# [lints]
# workspace = true
