[package]
name = "ethereum"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

alloy = { version = "0.6.4", features = ["full", "node-bindings"] }

[lints]
workspace = true
