[package]
name = "starknet-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

eyre = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
starknet = { workspace = true }

starknet-crypto = "0.7.3"

[lints]
workspace = true
