[package]
name = "starknet-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

thiserror = { workspace = true }
starknet = { workspace = true }
tracing = { workspace = true }
starknet-crypto = { workspace = true }

crypto-bigint = "0.5.5"
url = "2.5.4" 