[package]
name = "publisher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "update-mmr"
path = "bin/update_mmr.rs"

[[bin]]
name = "build-mmr"
path = "bin/build_mmr.rs"

[[bin]]
name = "extract-fees"
path = "bin/extract_fees.rs"

[dependencies]
guest-types = { path = "../guest-types" }
methods = { path = "../methods" }
common = { path = "../common" }
ethereum = { path = "../ethereum" }
mmr-utils = { path = "../mmr-utils" }
starknet-handler = { path = "../starknet-handler" }
ipfs-utils = { path = "../ipfs-utils" }

eth-rlp-types = { workspace = true }
# eth-rlp-verify = { workspace = true }

garaga_rs = { git = "https://github.com/keep-starknet-strange/garaga.git", branch = "main", default-features = false }
mmr = { git = "https://github.com/ametel01/rust-accumulators.git", branch = "feat/sha2-hasher" }
store = { git = "https://github.com/ametel01/rust-accumulators.git", branch = "feat/sha2-hasher" }
pyo3 = { version = "0.23.3", features = ["extension-module"] }

thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
sqlx = { workspace = true }
starknet-crypto = { workspace = true }
starknet = { workspace = true }
clap = { workspace = true, features = ["derive"] }
dotenv = { workspace = true }

risc0-zkvm = { version = "1.2.0" }
starknet-types-core = "0.1.7"
serde = "1.0"
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.2.0" }

[lib]
name = "publisher"
crate-type = ["cdylib", "rlib"]
