[package]
name = "ipfs-utils"
version = "0.1.0"
edition = "2021"
description = "IPFS utilities for handling MMR database files"
license = "MIT"

[dependencies]
tracing = { workspace = true }
thiserror = {workspace = true}
 
ipfs-api = "0.17.0"
tokio = { version = "1.28", features = ["full"] }
anyhow = "1.0"
futures-util = "0.3"

[dev-dependencies]
tempfile = "3.5"