[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = { workspace = true }
thiserror = { workspace = true }
dotenv = { workspace = true }

tracing-subscriber = "0.3.18"
starknet-crypto = "0.7.3"

# [lints]
# workspace = true
