[package]
name = "host"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "host"
# path = "src/lib.rs"

[[bin]]
name = "update_mmr"
path = "bin/update_mmr.rs"

[[bin]]
name = "build_mmr"
path = "bin/build_mmr.rs"

[dependencies]
guest-types = { path = "../guest-types" }
starknet-handler = { path = "../starknet-handler" }
methods = { path = "../methods" }
common = { path = "../common" }

garaga_rs = { git = "https://github.com/ametel01/garaga.git" }
mmr-accumulator = { git = "https://github.com/OilerNetwork/fossil-offchain-processor.git", branch = "block-validity-deps-segregation" }
db-access = { git = "https://github.com/OilerNetwork/fossil-offchain-processor.git", branch = "block-validity-deps-segregation" }
mmr = { git = "https://github.com/ametel01/rust-accumulators.git", branch = "workspace" }
store = { git = "https://github.com/ametel01/rust-accumulators.git", branch = "workspace" }

bytemuck = "1.14"
risc0-zkvm = { version = "1.1.3" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
dotenv = "0.15"
hex = "0.4"
anyhow = "1.0"
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum", tag = "v1.1.4" }
alloy = { version = "0.5.4", features = ["full"] }
eyre = "0.6"
risc0-groth16 = "1.1.2"
num-bigint = "0.4"
tokio = { version = "1.30", features = ["full"] }
starknet-crypto = "0.7.3"
async-trait = "0.1"
sqlx = "0.8.2"
tracing = "0.1"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.13"
block-validity = { git = "https://github.com/OilerNetwork/fossil-offchain-processor.git", branch = "block-validity-deps-segregation" }

[lints]
workspace = true
