[package]
name = "relayer"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }

alloy = { version = "0.6.4", features = [
    "providers",
    "network",
    "sol-types",
    "signer-local",
] }
alloy-contract = "0.6.4"
alloy-sol-types = { version = "0.8.12", features = ["json"] }
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.40"
eyre = "0.6"
thiserror = "2.0.3"

[lints]
workspace = true
