name: Cairo fmt
on:
  push:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    #   - uses: foundry-rs/setup-snfoundry@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.5"
      - run: cd contracts/starknet && scarb fmt --check
      - run: scarb fmt --check
      - run: scarb build
    #   - run: snforge test
