name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache RISC Zero toolchain
        id: cache-risc0
        uses: actions/cache@v3
        with:
          path: |
            ~/.risc0
            ~/.cargo/bin/cargo-risczero
          key: ${{ runner.os }}-risc0-v1

      - name: Install RISC Zero toolchain
        if: steps.cache-risc0.outputs.cache-hit != 'true'
        run: |
          curl -L https://risczero.com/install | bash
          export PATH="$HOME/.risc0/bin:$PATH"  
          rzup install
          rzup install cpp
          cargo install cargo-risczero --force
          echo "$HOME/.risc0/bin" >> $GITHUB_PATH

  fmt:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore RISC Zero cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.risc0
          key: ${{ runner.os }}-risc0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Add RISC Zero to PATH
        run: echo "$HOME/.risc0/bin" >> $GITHUB_PATH

      - name: Run format check
        run: cargo fmt --check

  clippy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore RISC Zero cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.risc0
          key: ${{ runner.os }}-risc0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Add RISC Zero to PATH
        run: echo "$HOME/.risc0/bin" >> $GITHUB_PATH

      - name: Run Clippy
        run: >
          cargo clippy 
          -p common 
          -p ethereum 
          -p guest-types 
          -p mmr-utils 
          -p relayer 
          -p starknet-handler 
          -- 
          -D warnings
          -W clippy::single_match
          -W clippy::single_match_else
          -W clippy::needless_match
          -W clippy::needless_late_init
          -W clippy::redundant_pattern_matching
          -W clippy::redundant_pattern
          -W clippy::redundant_guards
          -W clippy::collapsible_match
          -W clippy::match_single_binding
          -W clippy::match_same_arms
          -W clippy::match_ref_pats
          -W clippy::match_bool
          -D clippy::needless_bool
          -W clippy::unwrap_used
          -W clippy::expect_used

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore RISC Zero cache
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.risc0
          key: ${{ runner.os }}-risc0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add RISC Zero to PATH
        run: |
          export PATH="$HOME/.risc0/bin:$PATH"
          echo "$HOME/.risc0/bin" >> $GITHUB_PATH
          # Verify installation
          which rzup
          rzup show
          rzup toolchain list

      - name: Build
        run: cargo build --verbose

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore RISC Zero cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.risc0
          key: ${{ runner.os }}-risc0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add RISC Zero to PATH
        run: echo "$HOME/.risc0/bin" >> $GITHUB_PATH

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: cargo test --verbose
