name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-fmt-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install risczero toolchain
        run: |
          curl -L https://risczero.com/install | bash
          echo "$HOME/.risc0/bin" >> $GITHUB_PATH  # Add to PATH using GitHub Actions method
          echo "PATH=$HOME/.risc0/bin:$PATH" >> $GITHUB_ENV  # Ensure it's available for the session
          rzup install
          rzup install cpp

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run format check
        run: cargo fmt --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings
