name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-fmt-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install `sqlx-cli`
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Add DATABASE_URL environment variable
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo "DATABASE_URL is set"

      - name: Build
        run: cargo build --verbose

      - name: Prepare sqlx database query cache
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: cargo sqlx prepare --database-url $DATABASE_URL

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: cargo test --verbose

      - name: Run format check
        run: cargo fmt --check

      # - name: Run Clippy
      #   run: cargo clippy -- -D warnings

      - name: Run Clippy
        run: cargo clippy -p common -p ethereum -p guest-types -p mmr-utils -p relayer -p starknet-handler -- -D warnings
